#
#
#
#  ,---,.     ,---,.                                         ___
#  ,'  .' |   ,'  .'  \                                      ,--.'|_
#    ,---.'   | ,---.' .' |    ,---.      ,---.                  |  | :,'               __  ,-.
#      |   |   .' |   |  |: |   '   ,'\    '   ,'\    .--.--.      :  : ' :             ,' ,'/ /|   .--.--.
#    :   :  |-, :   :  :  /  /   /   |  /   /   |  /  /    '   .;__,'  /      ,---.   '  | |' |  /  /    '
#    :   |  ;/| :   |    ;  .   ; ,. : .   ; ,. : |  :  /`./   |  |   |      /     \  |  |   ,' |  :  /`./
#      |   :   .' |   :     \ '   | |: : '   | |: : |  :  ;_     :__,'| :     /    /  | '  :  /   |  :  ;_
#      |   |  |-, |   |   . | '   | .; : '   | .; :  \  \    `.    '  : |__  .    ' / | |  | '     \  \    `.
#    '   :  ;/| '   :  '; | |   :    | |   :    |   `----.   \   |  | '.'| '   ;   /| ;  : |      `----.   \
#      |   |    \ |   |  | ;   \   \  /   \   \  /   /  /`--'  /   ;  :    ; '   |  / | |  , ;     /  /`--'  /
#      |   :   .' |   :   /     `----'     `----'   '--'.     /    |  ,   /  |   :    |  ---'     '--'.     /
#      |   | ,'   |   | ,'                            `--'---'      ---`-'    \   \  /              `--'---'
#      `----'     `----'                                                       `----'
#
#                             .__        ____
#       _____ __  _  __ ____ |  |       /  _ \        ______ ____   ______  _  _____.__.
#       \__  \\ \/ \/ _/ __ \|  |       >  _ </\     /  ___//    \ /  _ \ \/ \/ <   |  |
#        / __ \\     /\  ___/|  |_     /  <_\ \/     \___ \|   |  (  <_> \     / \___  |
#       (____  /\/\_/  \___  |____     \_____\ /     ____  |___|  /\____/ \/\_/  / ____|
#            \/            \/              \/         \/     \/               \/
#

drops-item: EXPERIENCE_BOTTLE
experience-item: EXPERIENCE_BOTTLE
damage-item: EXPERIENCE_BOTTLE